services:
  db:
    image: postgres:16
    container_name: projeto-banquinho-bd
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: projeto_banquinho
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - projeto-banquinho-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/

volumes:
  projeto-banquinho-data: